# Generated by Django 5.2.15 on 2026-06-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('system', '系统通知'), ('friend_request', '好友请求'), ('friend_accepted', '好友请求接受'), ('comment', '评论'), ('like', '点赞'), ('reply', '回复')], max_length=20),
        ),
    ]
