<script setup>
import {
  Home, MessageCircle, MessageSquare, Users, User, UserPlus, UserCheck,
  Search, Bell, BellDot, Settings, LogOut, LogIn,
  Plus, X, Check, ChevronDown, ChevronRight, ChevronLeft,
  Heart, MessageCircleMore, Image as ImageIcon,
  Send, Pencil, Trash2, Eye, EyeOff,
  AtSign, Lock, Mail, Globe,
  Menu, MoreHorizontal, RefreshCw, Loader,
  AlertCircle, CheckCircle, Info,
  ArrowLeft, ArrowRight, ArrowUp, ArrowDown,
  Camera, Upload, Download, Link, Share2,
  Flag, ThumbsUp, Reply, Pin, Clock, Calendar,
  Hash, Tag, Bookmark, Filter, List, Grid as GridIcon,
  Sun, Moon, HelpCircle, FileText, Paperclip,
  Gift, Star, Copy, ExternalLink, Shield, AlertTriangle,
  BarChart3, Activity, Puzzle, ScrollText,
} from 'lucide-vue-next'

const props = defineProps({
  name: { type: String, required: true },
  size: { type: [Number, String], default: 20 },
  fill: { type: String, default: 'none' },
})

const iconMap = {
  home: Home,
  messageCircle: MessageCircle,
  messageSquare: MessageSquare,
  users: Users,
  user: User,
  userPlus: UserPlus,
  userCheck: UserCheck,
  search: Search,
  bell: Bell,
  bellDot: BellDot,
  settings: Settings,
  logOut: LogOut,
  logIn: LogIn,
  plus: Plus,
  x: X,
  check: Check,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  heart: Heart,
  messageCircleMore: MessageCircleMore,
  image: ImageIcon,
  send: Send,
  edit: Pencil,
  trash: Trash2,
  eye: Eye,
  eyeOff: EyeOff,
  atSign: AtSign,
  lock: Lock,
  mail: Mail,
  globe: Globe,
  menu: Menu,
  moreHorizontal: MoreHorizontal,
  refreshCw: RefreshCw,
  loader: Loader,
  alertCircle: AlertCircle,
  checkCircle: CheckCircle,
  info: Info,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  camera: Camera,
  upload: Upload,
  download: Download,
  link: Link,
  share: Share2,
  flag: Flag,
  thumbsUp: ThumbsUp,
  reply: Reply,
  pin: Pin,
  clock: Clock,
  calendar: Calendar,
  hash: Hash,
  tag: Tag,
  bookmark: Bookmark,
  filter: Filter,
  list: List,
  grid: GridIcon,
  sun: Sun,
  moon: Moon,
  helpCircle: HelpCircle,
  fileText: FileText,
  paperclip: Paperclip,
  gift: Gift,
  star: Star,
  copy: Copy,
  externalLink: ExternalLink,
  shield: Shield,
  alertTriangle: AlertTriangle,
  barChart: BarChart3,
  activity: Activity,
  puzzle: Puzzle,
  scrollText: ScrollText,
}
</script>

<template>
  <component
    :is="iconMap[name]"
    :size="size"
    :fill="fill"
    class="inline-block flex-shrink-0"
    aria-hidden="true"
  />
</template>
