# Generated by Django 5.2.15 on 2026-06-28 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_type_and_msg_type'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='groups.interestgroup'),
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat/files/'),
        ),
    ]
