# Generated by Django 5.2.15 on 2026-06-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic_tag',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', '公开'), ('friends', '好友可见'), ('private', '仅自己')], default='public', max_length=10),
        ),
    ]
